#!/bin/bash

# get serverlist and sort by longest first, so we match more specifically first
servers=$(vim --serverlist | perl -e 'print sort { length($b) <=> length($a) } <>')

# imposed by vim
MAX_SERVER_NAME_LENGTH=100

declare chosen_server

server_name=$(get-current-workspace)

for server in $servers; do
	if [ ! -z $(echo $server_name | grep $server) ]; then
		chosen_server=$server
		break
	fi
done

if [ ! -z $chosen_server ]; then
	echo "using existing vim server: $chosen_server"

	/usr/bin/vim --servername $chosen_server --remote-tab "$@"
else
	new_server_name=$(echo $server_name | head -c $MAX_SERVER_NAME_LENGTH)
	echo "new vim server: $new_server_name"
	/usr/bin/vim --servername $new_server_name "$@"
fi
